# Display message to the standard output
print("System Reboot complete")
print()
print("Hi..!! My name is Beep")
print()
print("I would like to ask some questions")
print()
print("May I ask some questions?")
answer = input("Enter yes or no: ")
if answer == "yes":
    print("✌(◕‿-)✌")
    print("Okay thanks")
elif answer == "no":
    print("Sorry but I need to ask you something")
else:
    print("Please enter yes or no.")
print("What is your name human?")
name = input()
print(f"Hi {name} its nice to meet you")
print("Please enter the number of experience you have in coding")
coding = int(input())
print(f"{coding}")
print("Please enter the number of skill level of your in Python?")
python = int(input())
print(f"{python}")
print("Please enter number of your IQ?")
IQ = int(input())
print(f"{IQ}")
print()
print("Database has been set")
print()
print(f"Coding: {'★' * coding}")
print(f"Python: {'✳' * python}")
print(f"IQ: {'❊' * IQ}")
