print("Please enter the number of lives")
lives = int(input())
print(f"{lives}")
print("Please enter the energy level?")
energy  = int(input())
print(f"{energy}")
print("Please enter the shield level?")
shield=int(input())
Shield = input()
print(f"{shield}")
print()
print("health has been set")
print()
print(f"Lives: {'♥' * lives}")
print(f"Energy: {'♦' * energy}")
print(f"Shield: {'♦' * shield}")